---
# Here you can edit the message join and color and you can edit permession for then !

# Tag on Message {name} for name player !
list:
 VIP:
  permission: "vip.msg"
  join: "{name} joined"
  quit: "{name} quit"
 Youtube:
  permission: "youtube.msg"
  join: "§f[§4YOUTUBE§4]§4 {name} Joined The Lobby !"
  quit: "§f[§4YOUTUBE§4]§4 {name} Leaved The Lobby !"
...
